name: Build and Push Image
run-name: Build and Push Image

on:
  push:
    branches:
      - main

jobs:
  build-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build image
        run: docker build -t imageku:latest .

      - name: List image
        run: docker images

      - name: Check image history
        run: docker history imageku:latest

      - name: Login to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.TOKEN_GITHUB }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Tag image
        run: docker tag imageku:latest ghcr.io/${{ github.repository_owner }}/imageku:latest

      - name: Push Image
        run: docker push ghcr.io/${{ github.repository_owner }}/imageku:latest
